global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'monitoring_server'
    static_configs:
      - targets: ['172.16.0.49:9100']

  - job_name: 'vms'
    static_configs:
      - targets:
          - '172.16.0.59:9100'
          - '192.168.200.81:9100'
          - '192.168.200.82:9100'
          - '172.16.0.60:9100'
          - '178.212.111.31:9100'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['monitoring_cadvisor:8080']

  - job_name: 'snmp_switches'
    metrics_path: /snmp
    params:
      module: [switches_mib]
    static_configs:
      - targets: ['10.20.0.179']
        labels:
          switch_name: 'H1F0R0U1a.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.182']
        labels:
          switch_name: 'H1F0R0U3.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.183']
        labels:
          switch_name: 'H1F0R0U4.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.184']
        labels:
          switch_name: 'H1F0R0U5.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.185']
        labels:
          switch_name: 'H1F0R0U6.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.186']
        labels:
          switch_name: 'H1F0R0U7.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.187']
        labels:
          switch_name: 'H1F0R0U8.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.188']
        labels:
          switch_name: 'H1F0R0U9.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.189']
        labels:
          switch_name: 'H1F0R0U10.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.190']
        labels:
          switch_name: 'H1F0R0U11.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.191']
        labels:
          switch_name: 'H1F0R0U12.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.193']
        labels:
          switch_name: 'H1F0R0U13.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.194']
        labels:
          switch_name: 'H1F0R0U14.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.195']
        labels:
          switch_name: 'H1F0R0U15.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.196']
        labels:
          switch_name: 'H1F0R0U16.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.197']
        labels:
          switch_name: 'H1F0R0U17.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.205']
        labels:
          switch_name: 'H1F0R0U18.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.229']
        labels:
          switch_name: 'H1F0R0U19.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.230']
        labels:
          switch_name: 'H1F0R0U20.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.233']
        labels:
          switch_name: 'H1F0R0U21.swhostel.lp'
          switch_type: 'HP'
      - targets: ['10.20.0.250']
        labels:
          switch_name: 'H1F0R0U22.swhostel.lp'
          switch_type: 'DLINK'
      - targets: ['10.20.0.253']
        labels:
          switch_name: 'H1FxUx.swhostel.lp'
          switch_type: 'DLINK'
      - targets: ['10.20.0.36']
        labels:
          switch_name: 'H8F5R1U2.swhostel.lp'
          switch_type: 'DLINK'
      - targets: ['10.20.0.37']
        labels:
          switch_name: 'H8F5R1U3.swhostel.lp'
          switch_type: 'DLINK'
      - targets: ['10.20.0.38']
        labels:
          switch_name: 'H8F5R1U4.swhostel.lp'
          switch_type: 'DLINK'
      - targets: ['10.20.0.40']
        labels:
          switch_name: 'H8F4R2U2.swhostel.lp'
          switch_type: 'DLINK'
      - targets: ['10.20.0.41']
        labels:
          switch_name: 'H8F4R2U3.swhostel.lp'
          switch_type: 'DLINK'
      - targets: ['10.20.0.42']
        labels:
          switch_name: 'H8F4R2U4.swhostel.lp'
          switch_type: 'DLINK'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116
