groups:
  - name: basic_alerts
    rules:
      - alert: HostDown
        expr: up{job="vms"} == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Host {{ $labels.instance }} is down"
          description: "Node Exporter has been down for more than 10 seconds."

      - alert: HighCpuLoad
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "High CPU load on {{ $labels.instance }}"
          description: "CPU load is {{ $value | printf \"%.2f\" }}%."

      - alert: NetworkSwitchOffline
        expr: up{job="snmp_switches"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Switch {{ $labels.switch_name }} is unreachable"
          description: "Switch {{ $labels.switch_name }} (IP: {{ $labels.instance }}) is not responding."

      - alert: SwitchPortDown
        expr: |
          (ifOperStatus == 2 and ifAdminStatus == 1 and ifType == 6)
          and
          (max_over_time(ifOperStatus[24h]) == 1)
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Port {{ $labels.ifName }} on {{ $labels.switch_name }} is down"
          description: "Interface {{ $labels.ifDescr }} DOWN."

      - alert: SwitchHighCpu
        expr: yrhCpuUtil1min > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU on {{ $labels.switch_name }}"
          description: "Load on CPU is {{ $value }}%."
