[vms]
172.16.0.59
192.168.200.81
192.168.200.82 ansible_user=den
172.16.0.60

[vms:vars]
ansible_user=toros
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
