[vms]
172.16.0.59
192.168.200.81
192.168.200.82
172.16.0.60

[vms:vars]
ansible_user=toros
ansible_ssh_private_key_file=/var/jenkins_home/.ssh/id_jenkins_git
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
