- name: Install Node Exporter on VMs
  hosts: vms
  become: no
  vars:
    node_version: "1.8.0"

  tasks:
    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /bin/false
        system: yes

    - name: Download binary
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_version }}/node_exporter-{{ node_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"

    - name: Extract archive
      unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Copy binary to bin folder
      copy:
        src: "/tmp/node_exporter-{{ node_version }}.linux-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        mode: '0755'
        remote_src: yes

    - name: Setup Systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable service
      systemd:
        name: node_exporter
        state: restarted
        enabled: yes
        daemon_reload: yes
