- name: Update Prometheus Configuration
  hosts: localhost
  connection: local
  vars_files:
    - list.yml

  tasks:
    - name: Generate prometheus.yml from template
      template:
        src: ../prometheus/prometheus.yml.j2
        dest: ../prometheus/prometheus.yml

    - name: Reload Prometheus configuration
      uri:
        url: http://prometheus:9090/-/reload
        method: POST
        status_code: 200
