- name: Update Prometheus Configuration
  hosts: localhost
  connection: local
  vars_files:
    - list.yml

  tasks:
    - name: Generate prometheus.yml from template
      template:
        src: /home/toros/monitoring/prometheus/prometheus/prometheus.yml.j2
        dest: /home/toros/monitoring/prometheus/prometheus/prometheus.yml

    - name: Reload Prometheus configuration
      uri:
        url: http://prometheus:9090/-/reload
        method: POST
        status_code: 200

    - name: Generate Alertmanager config from template
      template:
        src: /home/toros/monitoring/prometheus/alertmanager/config.yml.j2
        dest: /home/toros/monitoring/prometheus/alertmanager/config.yml

    - name: Reload Alertmanager
      command: docker restart alertmanager
